controller:
  publishService:
    enabled: "true" # This is required for external-dns to work
  admissionWebhooks:
    enabled: false

  hostPort:
    enabled: false
  service:
    type: LoadBalancer
