controller:
  publishService:
    enabled: "true" # This is required for external-dns to work
  admissionWebhooks:
    enabled: false

  # Use hostport for ingress so we don't need a LoadBalancer
  hostPort:
    enabled: true
  service:
    type: ClusterIP
