# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Maintain Python dependencies for building documentation
  - package-ecosystem: pip
    directory: /docs
    allow:
      # This is needed to update transitive dependencies as well as those in requirements.in
      - dependency-type: all
    schedule:
      interval: weekly
