# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

# Default cooldown is 3 days (ignored for security updates)
# https://github.blog/changelog/2026-07-14-dependabot-version-updates-introduce-default-package-cooldown/

version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  # Maintain Python dependencies for building documentation
  - package-ecosystem: pip
    directory: /docs
    allow:
      # This is needed to update transitive dependencies as well as those in requirements.in
      - dependency-type: all
    schedule:
      interval: weekly
    groups:
      docs-pip:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
