apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-secrets
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: gitea-secret
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: gitea-secrets                 # <-- AKV object name
        property: admin-username           # <-- property inside that object
    - secretKey: password
      remoteRef:
        key: gitea-secrets
        property: admin-password
