apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xk8tre-tls
  namespace: jupyterhub
spec:
  secretName: xk8tre-tls
  privateKey:
    rotationPolicy: Always
  commonName: jupyter.${DOMAIN}
  dnsNames:
    - jupyter.${DOMAIN}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer