apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jupyter-k8tre-tls
  namespace: jupyterhub
spec:
  secretName: jupyter-k8tre-tls
  privateKey:
    rotationPolicy: Always
  commonName: jupyter.base.k8tre.internal
  dnsNames:
    - jupyter.base.k8tre.internal
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer