apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-hub-to-k8s-api"
  namespace: jupyterhub
spec:
  description: "Allow JupyterHub hub pod to communicate with the Kubernetes API server"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: hub
  egress:
  - toEntities:
    - kube-apiserver
