apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-json-secret
  namespace: jupyterhub
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: guacamole-json-secret
  data:
    - secretKey: GUACAMOLE_JSON_SECRET_KEY
      remoteRef:
        key: guacamole-json-secret
        property: GUACAMOLE_JSON_SECRET_KEY
