apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8tre-tls
  namespace: keycloak
spec:
  secretName: keycloak.base.k8tre.internal-tls
  privateKey:
    rotationPolicy: Always
  commonName: keycloak.base.k8tre.internal
  dnsNames:
    - keycloak.base.k8tre.internal
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
