apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
  annotations:
    # Ensure secret is created before CNPG DB:
    # https://github.com/cloudnative-pg/cloudnative-pg/issues/6069
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store # name of the ClusterSecretStore to fetch the secrets from
  target:
    name: keycloak-db-secret # name of the k8s Secret to be created
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db-secret
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-db-secret
        property: password
    - secretKey: database
      remoteRef:
        key: keycloak-db-secret
        property: database
