apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

# See https://www.keycloak.org/operator/installation#_installing_multiple_operators
resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.2.1/kubernetes/kubernetes.yml
