- op: add
  path: /spec/template/spec/containers/-
  value:
    name: cmp-kustomize-envsubst
    command:
      - /var/run/argocd/argocd-cmp-server
    image: quay.io/argoproj/argocd:v2.13.3
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: tmp
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: plugin.yaml
        name: cmp-plugin
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: cmp-plugin
    configMap:
      name: cmp-plugin
