apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-with-envsubst
    spec:
      version: v1.0
      generate:
        command: [sh, -c]
        args:
          - |
            # Environment variables ENVIRONMENT and DOMAIN are passed from ApplicationSet via plugin.env
            # ArgoCD makes them available as $ARGOCD_ENV_<NAME> in the plugin container
            # Replace patterns: ${VAR}, .ENVIRONMENT., .DOMAIN, and standalone ENVIRONMENT/DOMAIN
            kustomize build --enable-helm --load-restrictor LoadRestrictionsNone . | \
            sed "s/\${ENVIRONMENT}/${ARGOCD_ENV_ENVIRONMENT}/g; s/\${DOMAIN}/${ARGOCD_ENV_DOMAIN}/g; s/\\.ENVIRONMENT\\./.${ARGOCD_ENV_ENVIRONMENT}./g; s/\\.DOMAIN/.${ARGOCD_ENV_DOMAIN}/g; s/^ENVIRONMENT$/${ARGOCD_ENV_ENVIRONMENT}/g; s/^DOMAIN$/${ARGOCD_ENV_DOMAIN}/g"
