apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cnpg
  namespace: argocd
spec:
  # Enable Go templating for dynamic field generation
  goTemplate: true
  # Configure template behavior - fail if a key is missing
  goTemplateOptions: ["missingkey=error"]

  # Define how applications are discovered and generated
  generators:
    - matrix:
        generators:
          - git:
              # Repository containing the application definitions
              repoURL: https://github.com/k8tre/k8tre.git
              # Use HEAD to always track the latest commit on the default branch
              revision: feature/vc-cnpg
              files:
                # Load the environment-specific values file
                - path: agnostics/cnpg/envs/*/values.yaml
              pathParamPrefix: config
          - matrix:
              generators:
                - git:
                    # Repository containing the application definitions
                    repoURL: https://github.com/k8tre/k8tre.git
                    # Use HEAD to always track the latest commit on the default branch
                    revision: feature/vc-cnpg
                    # Pattern to match directories for app discovery
                    directories:
                      # Matches any directory under agnostics/cnpg/envs/
                      # e.g., agnostics/cnpg/envs/prod
                      - path: agnostics/cnpg/envs/*
                    pathParamPrefix: env
                - clusters:
                    selector:
                      matchLabels:
                        # This will match the environment from the path segment
                        environment: "{{index .env.path.segments 3}}"

  template:
    metadata:
      name: "{{index .env.path.segments 1}}"
      annotations:
        # ArgoCD application name
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .env.path.segments 3}}"
        # Sync wave to control the order of application sync
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: default
      source:
        repoURL: https://github.com/cloudnative-pg/cloudnative-pg
        # Use the targetRevision value from the environment-specific values file
        targetRevision: "{{.config.cluster.targetRevision}}"
        path: releases
        directory:
          # Use the operatorVersion value from the environment-specific values file
          include: "{{.config.cluster.operatorVersion}}"
      destination:
        server: "{{.server}}"
        namespace: cnpg-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
