apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  # Enable Go templating for dynamic field generation
  goTemplate: true
  # Configure template behavior - fail if a key is missing
  goTemplateOptions: ["missingkey=error"]

  # Define how applications are discovered and generated
  generators:
    - matrix:
        generators:
          - git:
              # Repository containing the application definitions
              repoURL: https://github.com/k8tre/k8tre.git
              # Use HEAD to always track the latest commit on the default branch
              revision: main
              # Pattern to match directories for app discovery
              directories:
                # Matches any directory under agnostics/keycloak-operator/envs/
                # e.g., agnostics/keycloak-operator/envs/prod
                - path: agnostics/keycloak-operator/envs/*
          - clusters:
              selector:
                matchLabels:
                  # This will match the environment from the path segment
                  environment: "{{index .path.segments 3}}"

  template:
    metadata:
      name: "{{index .path.segments 1}}-{{.nameNormalized}}"
      annotations:
        # ArgoCD application name
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 3}}"
        # Sync wave to control the order of application sync
        # Lower numbers are synced first
        # This is set to 0 to ensure it syncs before other applications
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: default
      source:
        repoURL: https://github.com/k8tre/k8tre.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: keycloak-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
