apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: '{{ (index .ApplicationSetSourceObjectMap "ConfigMap" "repo-config" "data").repoURL }}'
              revision: main
              directories:
                - path: agnostics/sealed-secrets/envs/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{index .path.segments 3}}"
                matchExpressions:
                  - key: skip-sealed-secrets
                    operator: NotIn
                    values: ["true"]
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{.nameNormalized}}"
      annotations:
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 3}}"
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: default
      source:
        repoURL: '{{ (index .ApplicationSetSourceObjectMap "ConfigMap" "repo-config" "data").repoURL }}'
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
