apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage-class
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/karectl/karectl.git
              revision: main
              directories:
                - path: agnostics/storage-class/*/envs/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{index .path.segments 4}}"
                  vendor: "{{index .path.segments 2}}"
  template:
    metadata:
      name: "storage-{{index .path.segments 2}}-{{index .path.segments 4}}"
      annotations:
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 4}}"
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: default
      source:
        repoURL: https://github.com/karectl/karectl.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: storage-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
