apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    version: 4.2.0
    releaseName: jupyterhub
    namespace: jupyterhub
    valuesFile: values.yaml
      
resources:
  - ../../base
  # - netpol_singleuser_world.yaml

patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: k8tre-tls
