prePuller:
  hook:
    enabled: false # Disable prePuller hook - see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1621
hub:
  networkPolicy:
    egress:
      - ports:
          - port: 6443
          - port: 443
  config:
    JupyterHub:
      admin_access: true
      admin_users:
        - admin
proxy:
  service:
    type: ClusterIP
singleuser:
  cloudMetadata:
    # This requires elevated permissions which should be avoided. Use network policies instead.
    # See https://z2jh.jupyter.org/en/latest/administrator/security.html#audit-cloud-metadata-server-access
    blockWithIptables: false
  networkPolicy:
    enabled: false # These are managed by Cilium network policies
ingress:
  enabled: true
  hosts:
    - jupyter.dev.k8tre.internal
  ingressClassName: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jupyter.dev.k8tre.internal
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  tls:
    - hosts:
        - jupyter.dev.k8tre.internal
      secretName: jupyter-k8tre-tls

