apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    kubernetes:
      remoteNamespace: secret-store
      server:
        caProvider:
          type: ConfigMap
          namespace: external-secrets
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "external-secrets"
          namespace: "external-secrets"
