# Dev-specific configurations
debug:
  enabled: true
# Lower resource limits for dev environment
resources:
  limits:
    cpu: 500m
    memory: 512Mi
operator:
  replicas: 1

# Enable Hubble for observability
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    prometheus:
      enabled: true
    service:
      type: ClusterIP
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 31235
