apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-tls-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store # name of the SecretStore to fetch the secrets from
  target:
    name: keycloak-tls-secret # name of the k8s Secret to be created

  data:
    - secretKey: tls.crt
      remoteRef:
        key: keycloak-tls-secret
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: keycloak-tls-secret
        property: tls.key
