apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store # name of the SecretStore (or kind specified)
  target:
    name: keycloak-db-secret # name of the k8s Secret to be created
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db-secret
        property: username

    - secretKey: password
      remoteRef:
        key: keycloak-db-secret
        property: password

    # metadataPolicy to fetch all the labels and annotations in JSON format
    - secretKey: database
      remoteRef:
        metadataPolicy: Fetch
        key: keycloak-db-secret
        property: database
