apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - keycloak.yaml
  - postgres.yaml
  - keycloak-db-external-secret.yaml
  - keycloak-tls-external-secret.yaml
