apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

      
resources:
  - ../../base
  - postgres.yaml

patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: keycloak-k8tre-tls