# Workaround for https://github.com/bitnami/containers/issues/83267
image:
  repository: bitnamilegacy/keycloak
# Needed because we're overriding image above
# https://github.com/bitnami/charts/issues/30850
global:
  security:
    allowInsecureImages: true

postgresql:
  enabled: false
externalDatabase:
  host: keycloak-postgres-cluster-rw
  database: keycloak
  port: 5432
  existingSecret: keycloak-db-secret
  existingSecretUserKey: username
  existingSecretPasswordKey: password
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.k8tre-dev-eks.trevolution.dev.hic.dundee.ac.uk
  annotations:
    external-dns.alpha.kubernetes.io/hostname: keycloak.k8tre-dev-eks.trevolution.dev.hic.dundee.ac.uk
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  tls: true
  extraTls:
    - secretName: keycloak-k8tre-tls
      hosts:
        - keycloak.k8tre-dev-eks.trevolution.dev.hic.dundee.ac.uk
auth:
  adminUser: admin
  existingSecret: keycloak-admin-secret
  passwordSecretKey: admin-password

logging:
  level: DEBUG
