apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool 
spec:
  addresses:
  - 192.168.123.50-192.168.123.100 # This range should be adjusted to your network configuration
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
spec:
  ipAddressPools:
  - default-pool