# This ApplicationSet dynamically generates Argo CD Applications for JupyterHub
# production environments. It scans a Git repository for matching directory patterns
# and creates applications for each match.

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  # Name of the ApplicationSet resource
  name: jupyterhub
  # The ApplicationSet is created in the ArgoCD namespace
  namespace: argocd
spec:
  # Enable Go templating for dynamic field generation
  goTemplate: true
  # Configure template behavior - fail if a key is missing
  goTemplateOptions: ["missingkey=error"]

  # Define how applications are discovered and generated
  generators:
    - matrix:
        generators:
          - git:
              # Repository containing the application definitions
              repoURL: https://github.com/k8tre/k8tre.git
              # Use HEAD to always track the latest commit on the feature branch
              revision: main
              # Pattern to match directories for app discovery
              directories:
                # Matches any directory under apps/jupyterhub/envs/
                # e.g., apps/jupyterhub/envs/prod
                - path: apps/jupyterhub/envs/*
          - clusters:
              selector:
                matchLabels:
                  # This will match the environment from the path segment
                  # e.g., if path is apps/jupyterhub/envs/dev, it will match clusters with label environment: dev
                  environment: "{{index .path.segments 3}}"

  # Template for generating Application resources
  template:
    metadata:
      # Application naming pattern: <app-name>
      # e.g., jupyterhub
      name: "{{index .path.segments 1}}-{{.nameNormalized}}"
      annotations:
        # ArgoCD application name
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 3}}"
        argocd.argoproj.io/sync-wave: "0"
    spec:
      # Assign to the default project
      project: default
      # Source configuration for the application
      source:
        # Git repository containing the application manifests
        repoURL: https://github.com/k8tre/k8tre.git
        # Use the latest commit on the feature branch
        targetRevision: main
        # Path to the application manifests within the repository
        path: "{{.path.path}}"
      # Destination cluster and namespace to deploy the application
      destination:
        # Use the server URL from the matched cluster
        server: "{{.server}}"
        # Use namespace with pattern: <app-name>
        # e.g., jupyterhub
        namespace: jupyterhub
      # Sync policy for the application
      syncPolicy:
        automated:
          # Setting this to true will automatically delete resources that are no longer in Git
          # However, this breaks JupyterHub deployments as many resources are created by the application
          # and not managed by ArgoCD. So we set this to false. e.g., PVCs, singleuser server pods, etc.
          prune: true
          # Automatically sync if out of sync with Git
          selfHeal: true
        syncOptions:
          # Create namespace if it doesn't exist
          - CreateNamespace=true
