apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - agnostics/cert-manager.yaml
  - agnostics/cnpg.yaml
  - agnostics/external-dns.yaml
  - agnostics/external-secrets.yaml
  - agnostics/metallb.yaml
  - agnostics/nginx.yaml
  - agnostics/secret-store.yaml
  - agnostics/storage-class.yaml
  - identity/keycloak.yaml
  - workspaces/awms.yaml
  - workspaces/jupyterhub.yaml

patches:
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
  - target:
      kind: ApplicationSet
    patch: |-
      - op: add
        path: /spec/ignoreApplicationDifferences
        value:
          - jsonPointers:
              - /spec/syncPolicy
              - /spec/source/targetRevision
