apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Can't use the standard-install.yaml bundle because it includes tlsroutes v1 but
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/standard-install.yaml
  # Cilium expects v1alpha2 https://github.com/cilium/cilium/blob/v1.20.0-pre.0/operator/pkg/gateway-api/gateway_reconcile.go#L114

  # Required CRDs for GatewayAPI v1.4.1 (v1.5.0 not supported)
  # https://docs.cilium.io/en/v1.19/network/servicemesh/gateway-api/gateway-api/
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.4.1/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
